### ISSUE TITLE
Google terraform provider v5 support

### ISSUE THREAD

**Issue by kormide** [GoogleCloudPlatform/terraform-google-cloud-workflows#32]
This module is not compatible with the v5 google provider making it difficult to upgrade. See https://github.com/GoogleCloudPlatform/terraform-google-cloud-workflows/blob/main/versions.tf#L22. Is it possible to update the required provider config and release a new version?

**Comment by CaerusKaru** [comment]
Can a project maintainer please chime in here? Will we get 5.x support soon?
